### ISSUE TITLE
Remove or rewrite Administrator Dashboard

### ISSUE THREAD

**Issue by bubby932** [SubsurfaceStudios/CompensationAPI#485]
`administrator_dashboard.js` hasn't been used in well over 6 months, and most of our database schemas are either set in stone or easy to update with the MongoDB shell. For that reason, I don't think the Administrator Dashboard is necessary anymore, and any functionality we lose by removing it can be made up for by [the web dashboard](https://compensationvr.tk/admin).

@AveryOcean65 what are your thoughts on this?

**Comment by averyocean65** [comment]
Remove it :3

**Comment by bubby932** [comment]
great, thanks
